### ISSUE TITLE
JSON file on Android in clear text...

### ISSUE THREAD

**Issue by john-dalsgaard** [dan-eyles/sculejs#56]
I have the following setup:

```
var scule  = require('com.scule');
var password = 'blabla1234';
var protocol = 'scule+titanium://';
scule.debug(true);

// Return meta data collections
exports.baits = scule.factoryCollection(protocol+'baits', {secret:password});
```

Then in Android Device Monitor for the Android emulator I was running my app in, I opened the file `baits.json` in `/data/data/dk.dalsgaarddata.myapp/app_appdata` and found that it was in CLEAR text????

```
{"_sig":"18c92cbb7b635338b18cf56740b0aaf819737760","_salt":"19c120471ecd8d7935ef0fa3f9b3d3702c4a2bf6","_name":"baits","_version":3,"_objects":
	{"568f9d3133f68b0aad05dc07":
		{"userKey":"",
		"name":"Blink",
		"inActive":false,
		"key":"1",
		"unid":"F3FACF8B1AECF666C1257C200077F039",
		"created":"2013-11-11T22:50:03+0100",
		"createdBy":"John Dalsgaard/D-D",
		"modified":[],
		"modifiedBy":[],
		"timestamp":1384206603000,
		"sortTime":null,
		"_id":{"id":"568f9d3133f68b0aad05dc07","$type":"id"}
	},
etc....
```

That was quite unexpected! - What is then the purpose of the "secret" attribute - if not to "scramble"/encrypt the contents?

/John

**Comment by dan-eyles** [comment]
Hey John,

The secret is provided so that SculeJS can [sign the database files](https://en.wikipedia.org/wiki/Digital_signature#Integrity). This means that if the database is tampered with outside your application SculeJS will throw an exception next time it attempts to load data from disk.

If you need to store data on disk in an encrypted format it should be fairly trivial to implement a custom storage engine that encrypts/decrypts your data before storing and retrieving it.

I hope this clears things up.

Cheers,
Dan

**Comment by john-dalsgaard** [comment]
Ok, thanks...

I don't need encryption for this app, but I can easily foresee it in future projects - and must admit that I thought SculeJS did this ;-)
